# Generate machines_generated.cpp from machines/<name>.toml.
#
# The TOML is embedded BYTE FOR BYTE. This script does NOT understand TOML and
# must not learn to -- the C++ side parses it with loadTomlText(), the same
# parser that reads a config file off disk (config/toml.h). One machine
# language; a built-in cannot drift from a file, because it IS a file.
#
# The one thing this script does read is the FIRST COMMENT LINE, which becomes
# the one-line blurb in `swtpcsim --list`. That keeps the description next to
# the machine it describes, instead of in a table somewhere that goes stale.
#
# Inputs:  -DMACHINES_DIR=<dir> -DOUT=<file>

file(GLOB tomls "${MACHINES_DIR}/*.toml")
list(SORT tomls)

set(body "")
set(table "")

foreach(f ${tomls})
  get_filename_component(name "${f}" NAME_WE)
  string(MAKE_C_IDENTIFIER "${name}" sym)

  file(READ "${f}" text)

  # The blurb: the first `# ...` line, minus the hash.
  set(blurb "")
  string(REGEX MATCH "^#[ \t]*([^\n]*)" _m "${text}")
  if(_m)
    set(blurb "${CMAKE_MATCH_1}")
  endif()
  string(REPLACE "\\" "\\\\" blurb "${blurb}")
  string(REPLACE "\"" "\\\"" blurb "${blurb}")

  # Bytes, verbatim. A byte array rather than a C string literal: no escaping to
  # get wrong, no 65535-char limit, and the TOML can contain anything it likes.
  file(READ "${f}" hexstr HEX)
  string(REGEX REPLACE "(..)" "0x\\1," bytes "${hexstr}")
  string(LENGTH "${hexstr}" len)
  math(EXPR len "${len} / 2")

  string(APPEND body
    "static const unsigned char mach_${sym}[] = {${bytes}};\n")
  string(APPEND table
    "  { \"${name}\", \"${blurb}\", (const char*)mach_${sym}, ${len} },\n")
endforeach()

file(WRITE "${OUT}"
"// GENERATED by cmake/embed_machines.cmake -- do not edit.\n"
"#include \"core/machines.h\"\n"
"\n"
"namespace swtpc {\n"
"\n"
"${body}"
"\n"
"static const BuiltinMachine kMachines[] = {\n"
"${table}"
"};\n"
"\n"
"std::span<const BuiltinMachine> builtinMachines() {\n"
"  return std::span<const BuiltinMachine>(kMachines,\n"
"                                         sizeof(kMachines) / sizeof(kMachines[0]));\n"
"}\n"
"\n"
"} // namespace swtpc\n")

message(STATUS "embed_machines: wrote ${OUT}")
