# Generate roms_generated.cpp from roms/<NAME>/<image>.
#
# The image file is embedded byte-for-byte. This script does NOT understand
# Intel HEX and must not learn to -- the C++ side parses it with the same
# loader that backs the LOAD command (DESIGN.md 10.3.1).
#
# Inputs:  -DROMS_DIR=<dir> -DOUT=<file>

file(GLOB rom_dirs RELATIVE "${ROMS_DIR}" "${ROMS_DIR}/*")

set(body "")
set(table "")

foreach(d ${rom_dirs})
  if(NOT IS_DIRECTORY "${ROMS_DIR}/${d}")
    continue()
  endif()

  file(GLOB imgs "${ROMS_DIR}/${d}/*.HEX" "${ROMS_DIR}/${d}/*.hex"
                 "${ROMS_DIR}/${d}/*.BIN" "${ROMS_DIR}/${d}/*.bin"
                 "${ROMS_DIR}/${d}/*.S19" "${ROMS_DIR}/${d}/*.s19"
                 "${ROMS_DIR}/${d}/*.SREC" "${ROMS_DIR}/${d}/*.srec")
  list(LENGTH imgs n)
  if(n EQUAL 0)
    continue()
  endif()
  list(GET imgs 0 img)

  string(TOLOWER "${d}" name)
  string(MAKE_C_IDENTIFIER "${name}" sym)

  get_filename_component(ext "${img}" LAST_EXT)
  string(TOLOWER "${ext}" ext)
  if(ext STREQUAL ".hex")
    set(fmt "Format::Hex")
  elseif(ext STREQUAL ".s19" OR ext STREQUAL ".srec")
    set(fmt "Format::Srec")
  else()
    set(fmt "Format::Bin")
  endif()
  get_filename_component(base "${img}" NAME)

  # Bytes, verbatim.
  file(READ "${img}" hexstr HEX)
  string(REGEX REPLACE "(..)" "0x\\1," bytes "${hexstr}")
  string(LENGTH "${hexstr}" len)
  math(EXPR len "${len} / 2")

  # A one-line description for SHOW ROMS, read from roms/<NAME>/DESC -- one hand-written
  # line per ROM. Every built-in has one, so the column is uniform and each is visible
  # and editable in the tree rather than derived by a heuristic nobody can see. A ROM
  # with no DESC still builds (the column is just blank), but the warning says to add one.
  set(desc "")
  if(EXISTS "${ROMS_DIR}/${d}/DESC")
    file(READ "${ROMS_DIR}/${d}/DESC" desc)
    string(REGEX REPLACE "\r?\n.*$" "" desc "${desc}")   # first line only
    string(STRIP "${desc}" desc)
  else()
    message(WARNING "embed_roms: roms/${d} has no DESC file -- SHOW ROMS description will be blank")
  endif()
  # Escape for a C string literal.
  string(REPLACE "\\" "\\\\" desc "${desc}")
  string(REPLACE "\"" "\\\"" desc "${desc}")

  string(APPEND body
    "static const unsigned char rom_${sym}[] = {${bytes}};\n")
  string(APPEND table
    "  { \"${name}\", \"${base}\", ${fmt}, rom_${sym}, ${len}, \"${desc}\" },\n")
endforeach()

file(WRITE "${OUT}"
"// GENERATED by cmake/embed_roms.cmake -- do not edit.\n"
"#include \"core/roms.h\"\n"
"\n"
"namespace swtpc {\n"
"\n"
"${body}"
"\n"
"static const BuiltinRom kRoms[] = {\n"
"${table}"
"};\n"
"\n"
"std::span<const BuiltinRom> builtinRoms() {\n"
"  return std::span<const BuiltinRom>(kRoms, sizeof(kRoms) / sizeof(kRoms[0]));\n"
"}\n"
"\n"
"} // namespace swtpc\n")

message(STATUS "embed_roms: wrote ${OUT}")
